experiment:
  name: cancer_detection
  seed: 42
  device: cuda
  precision: float32

dataset:
  root_path: datasets/breakhis
  image_size: 224
  split_ratio: 0.15
  workers: 4
  
network:
  architecture: densenet121
  pretrained: true
  freeze_features: true
  num_classes: 2
  dropout: 0.3
  
optimization:
  algorithm: adamw
  learning_rate: 0.0001
  weight_decay: 0.01
  momentum: 0.9
  batch_size: 32
  accumulation_steps: 1
  
scheduler:
  type: cosine
  warmup_epochs: 3
  min_lr: 0.000001
  
training:
  epochs: 50
  patience: 15
  metric: val_accuracy
  mode: maximize
  
augmentation:
  horizontal_flip: 0.5
  vertical_flip: 0.3
  rotation_degrees: 15
  color_jitter: 0.2
  
normalization:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  
logging:
  tensorboard: true
  console_interval: 50
  checkpoint_interval: 5
  save_top_k: 3
  
paths:
  outputs: outputs
  checkpoints: outputs/checkpoints
  logs: outputs/logs
  predictions: outputs/predictions
